resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: every-morning
  type: time
  source:
    start: 9:40 AM
    stop: 9:45 AM
    location: America/Los_Angeles
    days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

- name: github-robbit-repo
  type: git
  source:
    uri: git@github.com:fyang-pivotal/robbit.git
    branch: master
    private_key: {{github-private-key}}

jobs:
- name: post-product-retro-items
  plan:
  - get: every-morning
    trigger: true
  - get: github-robbit-repo
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-robbit-repo
      run:
        path: python
        args:
        - "github-robbit-repo/src/post-retro-items.py"
        - {{product-postfacto-token}}
        - {{product-retro-id}}
        - {{slack-token}}
        - {{slack-channel-id-pks-telemetry-eng}}

